version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
